[workspace]
members = [
    "broker",
    "libpcap-tools",
    "libpcap-analyzer",
]

# [profile.release]
# opt-level = 'z'  # Optimize for size.
# lto = true
# codegen-units = 1
# incremental = false
# # panic = 'abort'