[package]
name = "rust-threeq"
version = "0.1.0"
authors = ["simon-fu <simonok@139.com>"]
edition = "2018"

# [[bin]]
# name = "rbench"
# test = false
# bench = false

# [[bin]]
# name = "rbroker"
# test = false
# bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
tracing = { version = "0.1", features = ["max_level_debug", "release_max_level_info"] }
tracing-subscriber = "0.2"
clap = "3.0.0-beta.2"
ntex-mqtt = "0.6.7"
mqttbytes="0" 
futures="0"
pretty_assertions = "0.6.1" # for tbytes
num_enum = "0.5.1"
ansi_term= "0.12"
